### ISSUE TITLE
Aspect ratio HUD fixes

### ISSUE THREAD

**Issue by Fruithapje21** [MaxLastBreath/TOTK-mods#101]
Awesome to see that you have found a new way to implement aspect ratios by increasing the horizontal resolution instead of just horizontal fov. However, the HUD fixes seem to have been removed. That's not really a problem for me as I can patch them right back in, but this might get confusing for others, especially when they might download a version of the hud fix that also changes the fovh again. I'm not sure what your long term plans are, but I can generate patches with hud fixes only if you are interested. Just lmk.

**Comment by MaxLastBreath** [comment]
Most of them still have the HUD fixes but they are a separate mod and usually not for every aspect ratio unfortunately i haven't found a way to make the UI unstretch properly in code, I did look for a while and I'm interested in doing so in the future, as that would make the mod even more complete than it is now. And to answer your question, I am interested if you want to make a pull request with some aspect ratio patches, I just don't have a lot of time lately, since i also started working on BOTW as well. 

You can clone the repo, the most important part is that they follow the name schemes already defined https://github.com/MaxLastBreath/TOTK-mods/tree/main/scripts/Mods/Aspect%20Ratios

If they follow the exact naming with all capital and everything the optimizer will pick them up automatically.

**Comment by MaxLastBreath** [comment]
oh there's also a zip.py converter script here too https://github.com/MaxLastBreath/TOTK-mods/blob/main/scripts/zip.py

**Comment by MaxLastBreath** [comment]
<3 feel free to contact me on discord if u want fruithapje, I wanted to ask you something as well.

**Comment by Fruithapje21** [comment]
Just created the pull request with the new files and some comments. I'll get to you on discord when I have the time <3

**Comment by MaxLastBreath** [comment]
Thank you very much! I hope to talk to you soon in Discord, everything is working as of now, also fixed the None issue, should be fully functional in 2.0.5 :D
