### ISSUE TITLE
please update for 1.2.1

### ISSUE THREAD

**Issue by asp0909** [MaxLastBreath/TOTK-mods#24]
Why are there no mods and cheats for tears of the kinddown 1.2.1??? Is there any problem with that update? I've searched and found almost nothing

**Comment by MaxLastBreath** [comment]
Everything except dfps is already and has already been ported to 1.2.1 (except the cheats)

The creator of dfps has disappeared and nobody can get in contact with them, therefore supporting 1.2.1 is pointless because you'll simply be playing an inferior version of the game, with no proper resolution/shadow resolution upscaling and more... I can't support the update unless the mod gets fully ported over, this is the reason. It's recommended to just use 1.2 or 1.1.2, I can use my version of dfps into the optimizer, but truth is, it is inferior to what dfps can do with resolution, it'll be much worse than just using Yuzu upscaler. If chuck were to make DFPS code available I'd gladly, no I'd love to just update it myself to make it all work with version 1.2.1, this is not the case, DFPS is compiled and nobody but chuck can update it and they have just disappeared for a good 2 months...

**Comment by asp0909** [comment]
I hope you are well...but what is happening with the cheats?

**Comment by MaxLastBreath** [comment]
> I hope you are well...but what is happening with the cheats?

I'll have to look into the cheats, I can port them over if, the other mod creators have them ready, maybe I'll put my version of dfps that works with 1.21 as well and just leave it at that, it's certainly just very sad situation that nobody but chuck has control over.

**Comment by enkrypt3d** [comment]
none of the cheats are working for me. the game launches, i have this optimizer pointed at yuzu, and still nothing.....

**Comment by MaxLastBreath** [comment]
> none of the cheats are working for me. the game launches, i have this optimizer pointed at yuzu, and still nothing.....

For the "cheats" you have to choose the TOTK version that you are using, as this is thread about 1.2.1, the optimizer as of right now isn't compatible with 1.2.1 (for now)

**Comment by enkrypt3d** [comment]
finding it difficult to find the 1.2.0 patch.... I'll keep digging thanks

**Comment by BooBerry** [comment]
You can find 1.2.1 cheats somebody updated on this fork here: https://github.com/Arch9SK7/NXCheats/tree/main

**Comment by MaxLastBreath** [comment]
Cheats have been updated to support 1.2.1 now.

**Comment by enkrypt3d** [comment]
The app does not launch. a CMD window appears and then quickly disappears on windows 11 pro x64. is there some order of operations to launch it?

**Comment by MaxLastBreath** [comment]
As noted in release notes, the auto updater seems to be bugging out, just reopen it and it should work

**Comment by enkrypt3d** [comment]
deleted the old version and got it launched but it does not appear to be applying cheats in 1.2.1 on Yuzu...... what am I missing? tried reloading the game, etc no luck

**Comment by MaxLastBreath** [comment]
> deleted the old version and got it launched but it does not appear to be applying cheats in 1.2.1 on Yuzu...... what am I missing? tried reloading the game, etc no luck

Select version 1.2.1 in the "Cheat" section of the manager.

**Comment by enkrypt3d** [comment]
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/93238214/b84d4db3-62d3-471d-b2b3-60f8d30a01f0)

I have 1.2.1 selected, tried launching the game without customizations..... still no luck... bummer. I've relaunched it several times. does it have to be run as admin?

**Comment by enkrypt3d** [comment]
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/93238214/b7d8893f-2f11-4ea8-92f6-1d33175f6689)
these are the mods i have installed. should this work?

**Comment by MaxLastBreath** [comment]
yes and the failure of those patches is a normal error message, u should just ignore it. As it says, applied cheats successfully lol

**Comment by enkrypt3d** [comment]
what am i doing wrong then? It should be working.... are any of these mods causing a conflict? I tried it with no mods with the same result....... game is running fine though in yuzu.

**Comment by MaxLastBreath** [comment]
[Full support for 1.2.1 with new upscaling tech. Select New on the upscaling to make 1.2.1 work.](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.4.0)
