### ISSUE TITLE
Trojan on the mod?

### ISSUE THREAD

**Issue by HQSantosilva** [MaxLastBreath/TOTK-mods#38]
I've analyzed the .exe file with virus total and the results were positive for some antiviruses.
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/110571779/6f8063c5-7476-4400-92fe-3f66b9cd4623)

**Comment by MaxLastBreath** [comment]
Now go clone the repo, compile an exe and compare. False positive, 5 shitty antiviruses that nobody uses using shitty AI detection algorithms, look into the real antivirus programs, malware bytes and bitdefender.

**Comment by tadaskarpavicius** [comment]
Well, chrome does not allow me to download any of the release files because of this false positive (windows security marked files as containing trojan) , so maybe this should be looked into...
![Screenshot 2024-06-25 195523](https://github.com/MaxLastBreath/TOTK-mods/assets/2151969/7d1466c9-66b0-47f6-aae3-15de8280c30b)

**Comment by MaxLastBreath** [comment]
Ps you can always download the source code and run it from source
