### ISSUE TITLE
scaling problem

### ISSUE THREAD

**Issue by Remonli** [MaxLastBreath/TOTK-mods#7]
Hi,pls check the scaling problem on my screen , 2240X1400 , with system scaling 150% 

![图片](https://github.com/MaxLastBreath/TOTK-mods/assets/9067053/bd55486c-0152-4073-9bc9-7f8997f2683f)

**Comment by MaxLastBreath** [comment]
I'll look into it later today, scaling turned out pretty problematic, thank you for reporting this. Going to try to fix it asap.

**Comment by MaxLastBreath** [comment]
A new hotfix has been uploaded that should fix this issue. Upon opening the program again you will be prompted to auto update :) or just download from [here](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.2.2)

**Comment by Remonli** [comment]
It's better, but not perfect on my screen(2240*1400 150%),could you pls check if there any improvement？

![图片](https://github.com/MaxLastBreath/TOTK-mods/assets/9067053/c8143dc1-d372-4efd-a77b-b0b32d16513b)

**Comment by MaxLastBreath** [comment]
Yeah it's probably scaling at 100% the ui itself looks as intended which is an improvement to what was previously shown, I know the solution and how to integrate both the auto scaling and windows scaling but that will have to be for another update that will add a customization into the mod manager, like it's own setting tab that you can configure various behaviors I'm just happy it's consistent across different scaling/resolutions now (it took me a few hours to get it right).

But yeah I've disabled system scaling for now entirely because it was causing various different issues, I'm pretty sure i have it figured out now though, the groundwork is layed down and I'll just have to configure the function, it's just going to take a little bit of time to implement the entire feature set. It's definitely coming though.

Thank you for your report it greatly helps improve the project.

**Comment by MaxLastBreath** [comment]
[Commit b68234a](https://github.com/MaxLastBreath/TOTK-mods/commit/b68234acfc9099c29cc90ed95e148dce9e5640d6#diff-9f491157f33517dbbb9448c53269c87a10352bc03bcd370db65ac54393978e59) addresses scaling issues and adds different scaling options in the new settings menu, itll be all pushed with version 1.3.0 Im still in the middle of going through everything and not yet fully happy with things for release 1.3.0 :). If you are facing any other issues let me know, as im actively cleaning and polishing the code and fixing issues currently for 1.3.0.

**Comment by MaxLastBreath** [comment]
[Version 1.3.0](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.3.0) Fixes all scaling issues as well as giving different scaling options in the Setting menu! :)
