### ISSUE TITLE
Freeze after clearing the Wind temple

### ISSUE THREAD

**Issue by Ariane-B** [MaxLastBreath/TOTK-mods#8]
After beating the boss of the Wind temple, you get an autosave, where you can pick up the heart container and talk to your companion. I pick up the heart container, talk to my companion, and then I get a chain of cutscenes involving characters from the distant past and my companion.

Then, there's a pretty long loading screen, where it's preparing the cutscene of Rito Village returning to normal. That's where it freezes, with Yuzu's frametime reading "nan".

I'm including [Yuzu logs](https://github.com/MaxLastBreath/TOTK-mods/files/12388388/yuzu_log.zip) of what happened from me loading up the autosave to the freeze. I can't really give you extended logs. Enabling extended logs completely wrecks the textures (including the ones from the snow falling), which makes me entirely unable to see wherever the heck I'm going. Even just including the ones from the current run (not "old") makes a pretty big file, so please excuse the very compressed .zip. Otherwise I'd have blown GitHub's limit.

Ah, by the way, this is what my TOTK Optimizer looks like.

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/6244273/d4d3c2e8-0002-40c3-b3b1-4554b9b554ce)

Anyway, initially I though it was simply the "experimental" part of Yuzu, but no. The minute I right-click the game and uncheck all of the mods added by TOTK Optimizer, I can get through the long cutscene and see the snow melting just fine.

I don't know what's wrong but it seems the mods are doing something, somewhere, to make the game crash at that exact point.

EDIT: If it helps with tests, here's my save folder. It should include the autosave I was using for testing as the latest save.

[0100F2C0115B6000.zip](https://github.com/MaxLastBreath/TOTK-mods/files/12388403/0100F2C0115B6000.zip)

**Comment by MaxLastBreath** [comment]
Hey I know u are looking for help but this issue is unrelated to mods or the TOTK Optimizer, regardless. Someone else had this issue a long time ago ( 2-3 months ago) and i was able to help them by playing on their save and getting past the cutscene of the wind sage, Im not sure what is causing this but it is most likely an issue caused by DFPS on very particular yuzu version/game version, regardless this is unrelated to the Optimizer. Its a very, very rare bug in that particular cutscene (only this one as far as im aware, and no way to replicate or even know whats exactly causing it).

[For more bugs you can refer to this thread, Im also running it but havent had the time to get it up to date.](https://www.reddit.com/user/Maxlastbreath/comments/148p4wh/yuzu_totk_bugmegathread/)

**Comment by Ariane-B** [comment]
Oh, I wasn't really looking for help. More like trying to help resolve it with logs and save files. 

The bug is easily worked around by temporarily disabling mods, after all. 

I'm glad you could narrow the issue down to DFPS though! I'll forward this to the author. Maybe it'll help them.

**Comment by MaxLastBreath** [comment]
Yeah Im assuming its a problem with 60+ FPS, 60+ fps has similar issues that are present on 1.0.0 (Game permanently freezes when you die, etc) Also cutscenes freezing as well.. Did you by any chance also use uncapped FPS? This can be very unstable. 

Also if you have any problems with the optimizer feel free to open another issue thread as Im very keen on fixing everything :).

**Comment by Ariane-B** [comment]
Hmm no it was capped at 60!

Thanks :) I've already added a comment on the thread for the latest stable version of DFPS so hopefully my info helps them understand the issue.

**Comment by MaxLastBreath** [comment]
Hope it's figured out! Although it's just a really hard issue to replicate
